---
title: "網頁剖析"
date: '2019-12-12'
output:
    html_document:
        number_sections: no
        theme: united
        highlight: tango
        toc: yes
        toc_float:
            collapsed: no
        css: style.css
        md_extensions: +implicit_figures
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T,
                      results = 'hide',
                      comment = '#>',
                      message = F,
                      out.width = '80%',
                      fig.align = 'center')
library(ggplot2)
```

```{js echo=FALSE}
window.onload = () => {
        document.querySelectorAll('.hide').forEach(ele => {
            ele.className = 'note';
        })
}
```

## Openning

<div class="hide" data-tag="Openning">
</div>


## Review CSS

<div class="hide" data-tag="child.html">
1. Review: nested structure of `<ol>`, CSS
    - 4 children (2 grandchildren)
    - `<style>`
1. Change outer `<ol>` to `<ul>` (becomes nested `<ul>`)
    - How to style inner `li` (under the second `ul`)
    
    ```css
    ul > li {
        color: red;
    }

    ul > ul > li {
        color: red;
    }
    ```

    - Composing child selector

1. Add `<a>` in `<li>` (explain link)

    ```html
    <ul>
        <li>list item one</li>
        <li>list item two</li>
        <ul>
            <li>sublist item one</li>
            <li>
                I want <a href="https://google.com">this link</a> styled
            </li>
        </ul>
        <li>list item three</li>
    </ul>

    <ul>
        <li>
            I don't want <a href="https://google.com">this link</a> styled
        </li>
    </ul>
    ```

    ```css
    ul > ul > li > a {
        color: green;
    }
    ```
</div>

## Your Turn

`imt.html`: style web site link

- 說明
    - decompose: 3 part, `div.institute`, `ul.member`, `footer`
    - css: what makes the web site looks differently (list --> block)
        - 不用管其它的，只看最上面

- **3 min**

- Explain

## rvest

<div class="hide" data-tag="rvest">
1. Review `httr`

    ```r
    library(httr)
    library(rvest)

    req <- GET("https://rlads2019.github.io", 
               path = c("14", "child3.html"))
    req[["status_code"]]
    html <- content(req)
    ```

1. rvest basics

    ```r
    library(rvest)
    html %>% html_nodes("head") %>% html_nodes("title")
    html %>% html_nodes("head") %>% html_nodes("title") %>% html_text()

    # Try different CSS selectors
    html %>% html_nodes(".institute")
    html %>% html_nodes(".institute > img")
    html %>% html_nodes(".institute > img") %>% html_text()  # empty string
    html %>% html_nodes(".institute > img") %>% html_attr("src")
    html %>% html_nodes(".institute > img") %>% html_attr("alt")

    html %>% html_nodes("ul.member > li > ol > li > a")
    html %>% html_nodes("ul.member > li > ol > li > a") %>% html_text()
    html %>% html_nodes("ul.member > li > ol > li > a") %>% html_attr("href")
    ```
</div>


## Your Turn 

從你上次的作業抓出「姓名」、「系級」、「學號」 --> 在 R 中變成 3 個字串 (3 chr vectors)

- Demo: IVO

    ```r
    req <- GET("https://ivotung1129.github.io/my_webpage/index.html")
    req[["status_code"]]
    html <- content(req)

    id <- html %>% html_nodes("#identity") %>% html_text() %>% strsplit(" ") %>% .[[1]]
    dept <- id[1]
    id_num <- id[2]
    student <- id[3]
    ```

## Web devtools

<div class="hide" data-tag="devtools">

**slide**

- 實際的網頁很複雜，要如何**快速**找到自己想要的資料的 CSS selector

**demo: chrome**

- chrome devtools
- target: footer rlads2019 link (under `p.copyright`)

**demo: r**

```r
req <- GET("https://rlads2019.github.io/lab/")
req[["status_code"]]
html <- content(req)

html %>% html_nodes("p.copyright > a")
html %>% html_nodes("p.copyright > a") %>% html_text()
html %>% html_nodes("p.copyright > a") %>% html_attr("href")
```
</div>

## 不必凡事都親自動手 (用別人寫好的套件)


## 課程總結 (實習課的期待)

- R 程式基礎, 資料分析, 文本分析
    - base R, `tidyverse`, `quanteda`
- 使用 GitHub 管理程式碼
    - GitHub Desktop (作業繳交)
    - (上週) 請大家自行建立一個 GitHub Repo
- 將努力成果 (透過網頁) 保存與分享
    - R Markdown, GitHub, GitHub Pages

(兩年前，我 3 個期待都無法達成)

1. (你**不笨**，不要挫折) Lab is hard, 20hr-5hr you are smart 
2. (如果寫程式很**痛苦**，很抱歉，我是第一次教程式，不太會拿捏，所以給了同學相當大的壓力)
    - 記得謝老師上課說過：寫程式應該是很快樂的事
    - 如果你真的覺得過程很痛苦，你可以試試看回想寫程式的過程中有沒有那麼一丁點、一瞬間的快樂
    - 如果有的話，請努力記住這快樂，因為寫程式的痛苦會過去，而且只會越來越少，但樂趣會越來越多。
    - 同學可能這學期因為課業壓力太大，無法靜下心來體會寫程式的快樂。但我相信能撐到現在，就代表大家有那個潛力可以發現寫程式的樂趣。
    - 我覺得「抓到」這個寫程式的樂趣，才是「學會」寫程式的關鍵
    - 對於學期初沒有程式基礎，但現在還留著的同學，你們已經走過學習寫程式**最辛苦**的階段，接下來的過程應該會越來越有趣
3. 這學期剩下的期末專案是個很好的機會。從現在開始，大家不是為了學程式而寫程式，而是為了**解決問題**而寫程式。
    - 這過程中，大家可能會遇見新的問題，需要接觸許多自己沒看過的東西
    - 但請不要害怕，我知道大家的基礎很好 (真的，從一些來問問題的同學，我發現你們進步的很快)
    - 大家會缺乏的不是能力，而是一些自信和勇氣而已
    - 最後和大家分享一張圖片，這是我當初在學習寫程式的時候，常常會有的一種感覺，我覺得這張 GIF 描繪的很生動
        - 就是我常常會遇到自己完全不懂、不敢接觸的東西，覺得自己不可能會理解它如何運作。但當我終於深呼吸一口、靜下心來，嘗試去理解這個東西的時候，我常常發現這個東西比我想像中的還來的簡單許多。而且過程中還會有意想不到的收穫。
