---
title: "Strings & Regular Expression (W8)"
date: '2019-10-31'
output:
  html_document:
    number_sections: no
    theme: united
    highlight: tango
    toc: yes
    toc_float:
      collapse: no
    css: style.css
    md_extensions: +implicit_figures
    includes:
      in_header: "../GA.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment = '#>',message = F, out.width = '70%', fig.align='center')
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'),color = 'darkred', lang=c('r', 'txt'))
```

## Character classes: `\d`, `\s`, `\S`, `[]`, `[^]`

```{r results='asis', echo=FALSE}
library(dplyr)
news <- readLines('corpus/news_first_para.txt') %>%
  paste0(collapse = '\n')

paste0('```txt\n', news, '\n```') %>%
  writeLines()
```

- `\s`

  ```regex
  
  ```

- `\S`

  ```regex
  【\S+╱\S+報導】
  ```

- `\d`

  ```regex
  \d+%
  ```

- `\d`

  ```regex
  [0-9.]+%
  ```

```{r}
library(stringr)
str_view_all(news, '[0-9.]+%')
```


