---
title: "Regular Expression & Stringr (W8)"
date: '2019-10-31'
output:
    html_document:
        number_sections: no
        theme: united
        highlight: tango
        toc: yes
        toc_float:
            collapsed: no
        css: style.css
        md_extensions: +implicit_figures
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T,
                      results = 'hide',
                      comment = '#>',
                      message = F,
                      out.width = '80%',
                      fig.align = 'center')
library(ggplot2)
```

```{js echo=FALSE}
window.onload = () => {
        document.querySelectorAll('.hide').forEach(ele => {
            ele.className = 'note';
        })
}
```


## 工作目錄提醒

<div class="hide" data-tag="slide, demo, slide">

1. working dir 很重要
2. 它決定了你在讀取檔案時的"相對路徑"要如何撰寫
    e.g. GUI --> readr path
3. 但是 Rmd 在 knit 的時候，它會另外再開一個 R session, 然後把工作目錄設置在該 Rmd 檔所在的資料夾
4. 養成好習慣：一進到 RStudio 就要重設 Working directory
5. 期中考洩題：相對路徑
</div>


## 正課 Openning

<div class="hide" data-tag="Slide">
1. 進入「非結構化」資料
    - 資料雜亂 -->  
    具備基本能力，從雜亂的資料裡找出規律，透過這些規律抓出你要的東西

1. 新聞資料 -->  
看似沒規律但還是找得到一些規律 -->  
抓出記者姓名

1. Regular Expression 是一套語法，
    - 用來「描述我們在文字裡看到的規律」
    - 透過這個規律，從一大串文字裡面，抓出符合這個規律的文字

1. Regex 和 程式語言沒有關聯

1. 點擊連結: 提醒 g 和 m 要打勾
</div>

## Basics

<div class="hide" data-tag="萬用字元">

```
我妹妹很正
你妹妹超正
我妹妹 正
他妹妹超級正
```

1. plain text matching: `妹妹`
1. 萬用字元: `妹妹很正` --> `妹妹.正` --> `妹妹..正`
    - 提醒：空白也是字
</div>

<div class="hide" data-tag="Group and or">
語料續上

1. 如何 Match 很、超級、非常 (忽略空白)？
    1. 用括號製造一個單位：`(很)正` --> 單位內會優先處理
    2. 加入「或」：`(很|超)正` --> `(很|超|超級)正`
</div>

<div class="hide" data-tag="Anchor">
```
你妹妹很正嗎？
我妹妹比我還正
```

1. 開頭：`我` --> `^我`
1. 結尾：`正` --> `正$`
</div>

<div class="hide" data-tag="Escape">
```
我妹妹超.級.正
我妹妹超～級～正
我超正 ^^
```

1. 目標找出 `超.級.正`
1. `超.級.正` --> ask why both are matched
1. `超\.級\.正`

1. `^^` --> `\^\^`
</div>

**2 min**

## Repetition

<div class="hide" data-tag="+ ?">
```
我妹妹超正
我妹妹超級正
我妹妹超超超超正
```

1. `超正` --> `超+正`: 1 次或是 1 次以上
1. `超級正` --> `超級?正`
1. 結合：`超+級?正`
</div>

<div class="hide" data-tag="{num}">
```
今天是 2019-10-31
今天是 2019-02-10
今天是 2019-01-01
```

1. 想抓出日期 --> 引入 `\d` --> `\d\d\d\d-\d\d-\d\d`
1. `+` 號 `\d+-\d+-\d+` --> 語料加入 `02-3366-3366` --> Exact number --> `\d{4}-\d{2}-\d{2}`
1. 日期格式可以有很多種 --> 刪除語料中的 `0`
1. num range `\d{4}-\d{1,2}-\d{1,2}`
</div>


## Character classes

1. Link from `\d` --> character class 指可以代表多個字元

<div class="hide" data-tag="white spaces">
```
One white space between each word.
One tab between each word.
Two  white  spaces  between  each  word.
```

1. `each word` --> `each\sword` --> `each\s+word`
1. non-whiter space: `\S`
</div>

<div class="hide" data-tag="bracket">
```
The cat in the hat.
A1 B1 C1 D1 E1 F1
a1 a2 a3 a4 a5 a10
```

1. `the` --> `[Tt]he`
    - 讓你自行定義 **character class**
1. `a[123]` --> `a[1-3]` --> `a[^1-3]`
1. `[BCD]1` --> `[B-C]1`
</div>

**3 min**: your turn (slide)

```
【賴德剛╱綜合報導】
大聯盟勞資協議昨獲共識，要繳交超出部分的17.5%稅額，連續第2年則課30%，連續第3年40%，第4年起都是50%。新版協議，第1年稅額調高為20%，第2年不變，第3年起都是50％。

【曾雪蒨╱台中報導】
一名35歲OL是「3C控」，白天上班打電腦、訊軟體聲響，竟忍不住低頭滑手機看內容...

【蔡裕隆╱彰化報導】
台灣啤酒「台版天兵麥基(JaVale McGee)」周伯勳，昨出戰臺灣銀行，轟出全隊次高...

【韓政燕╱綜合外電報導】
日本前晚從鹿兒島縣種子島宇宙中心成功發射搭載無人補給太空船「鸛」6號的...

【國際中心╱綜合外電報導】
今年美國總統大選期間，大量假新聞充斥推特、臉書等社交網站，遭質疑扭曲真相...

【鍾裕能╱綜合報導】
巨人季後簽了陽岱鋼、山口俊、森福允彥共3名自由球員，又網羅前樂天大砲...
```


## Backreference

<div class="hide" data-tag="backref">
```
防不勝防
精益求精

快點快點
慢來慢來
```

1. 成語結構 --> 找出結構相同的成語
1. 在 regex 上如何達成？我不知道確切的字為何，只知道第 1 個字和第 4 個字一樣
1. `\S\S\S\S` --> `(\S)\S\S\1`
1. `(\S)(\S)\1\2`
</div>

**3 min**: your turn (slide)

```
一口接一口
一口接著一口
一口接著又一口
一巴掌接著一巴掌

一口接著一巴掌
```

1. `一口接著一口`
1. `一(口|巴掌)接著一口`
1. `一(口|巴掌)接著一(口|巴掌)`
1. `一(口|巴掌)接著?又?一\1`

## Stringr

<div class="hide" data-tag="slide, demo">
**slide**

1. 只講 3 個函數，剩下請同學自行嘗試看看

**demo**

1. `str_detect()`, escape regex: 在 regex 的每條反斜線之前再加上一條反斜線
    
    ```r
    # Basics: return true false
    str <- c("cat", "bed", "car", "Mr.")
    str_detect(str, "a")
    
    # 篩選資料
    str_detect(str, "^c")
    str[str_detect(str, "^c")]
    
    # Escape
    str_detect(str, "\.")
    str_detect(str, "\\.")
    ```

1. `str_match()` (`str_match.R`)

    ```r
    str <- c("Won't match.", "One two three, four five six.", "Seven eight nine.")
    result <- str_match(str, "([a-zA-Z]+) ([a-zA-Z]+) ([a-zA-Z]+)")
    
    # Extract result
    result[1, ]  # first match
    result[2, ]  # Second match
    
    # Full result
    result[2, 1]
    
    # Group
    result[2, 2]  # first group
    result[2, 3]  # second group
    ```

1. `str_match()` 只 match 到一個 --> `str_match_all()`

    ```r
    result <- str_match_all(str, "([a-zA-Z]+) ([a-zA-Z]+) ([a-zA-Z]+)")
    
    # 每個 sub-list 裡面儲存的是一個 matrix
    result[[2]]
    
    # 第一個結果
    result[[2]][1, ]
    ```
</div>
