---
title: "Vector, Data types, if-else (W3)"
date: "2019-09-26"
output:
  html_document:
    number_sections: no
    theme: united
    highlight: tango
    toc: yes
    toc_float:
      collapsed: no
    css: style.css
    md_extensions: +implicit_figures
    includes:
       in_header: "../GA.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = '#>',
                      message = F)
```


```{js echo=FALSE}
window.onload = () => {
        document.querySelectorAll('.hide').forEach(ele => {
            ele.className = 'note';
        })
}
```

## Intro to Vector

<div class='hide' data-tag='Intro to Vector'>
1. Vector 是 R 裡面最基礎的運算的單位
1. 上週實習課：主要使用**單一數值**去做運算, e.g. 四則運算
1. **單一的數值**雖然看起來像是「一個」數字，但它在 R 裡面就是 vector，只是是一個長度為 1 的 vector
1. 已接觸過長度大於 1 的 vector：上週實習課 `11:51`、作業的 `seq()`
1. 6 種類型的 vector，常見的有 4 種
</div>

## Demo: Vector

<div class='hide' data-tag='Demo Vector'>
1. Useful functions to work with vectors

    ```r
    length(1)
    length(1:10)

    c(-1, 5, 3)
    c(1:5, 3)  # 壓平

    typeof(1:10)
    ```

1. integer & double

    ```r
    c(1L, 3L, 5L)
    typeof(c(1L, 3L, 5L))
    typeof(c(1, 3, 5))
    ```

    1. 在 R 裡面 integer 和 double 合稱為 numeric，多數情況下不需要去太在意兩者的區別， R 會自動幫你做轉換, e.g. `1L / 2L`

    ```r
    Inf
    1 / Inf
    Inf / Inf
    log(-1)
    ```

1. Element-wise operation

    ```r
    vec1 <- 1:3
    vec2 <- 3:5

    vec1 + vec2
    ```

    - **slide**


1. character

    ```r
    "Hello world!"
    c("Hello world", "1.1")
    
    "\""
    '"'
    "'"
    ```

1. logical

    ```r
    # 布林值
    TRUE
    FALSE
    T
    F

    # logical tests, 進行邏輯運算, 像是比較兩個 numeric vector 的大小
    vec1 <- c(1, 1, 1)
    vec2 <- c(2, 0, 2)
    
    vec1 > vec2
    vec1 < vec2
    vec1 == vec2
    ```

    - **slide**: logical operators
    
    - **slide**: boolean operators
        
        - 取得 logical vector 之後，可以進一步對 logical vector 裡面的布林值進行運算，這時就需要所謂的**布林運算子** (AND, OR, NOT)
        - **back to RStudio**
    
    ```r
    TRUE & TRUE
    TRUE & FALSE
    TRUE | FALSE
    !TRUE

    (1 == 1) & (2 == 2)
    ```
</div>

**3 min**

---

## NA value

<div class='hide' data-tag='NA value'>
1. NA, Not Available, 缺失值
1. 可作為任何一種 vector 裡面的元素
1. NA 出現在 vector 中，常會造成意外的結果

```r
10 > NA
NA == NA

vec <- c(1, NA, 2, 3)
mean(vec)
mean(vec, na.rm = TRUE)
```
</div>


## Recycling

<div class='hide' data-tag='Recycling'>
1. 前面介紹過 R 的 vector 是以 element-wise 的方式去進行運算的，
1. 所以譬如說，我們可以將兩個長度相同的 numeric vector 加起來，就會得到另一個長度相等的向量
1. 那如果在 R 裡面，我們將不同長度的 vector 加起來的話，會發生什麼事？

```r
11:13
11:13 + 10
```

1. **slide**: animation

1. **slide**: `paste0()`

1. pop quiz
</div>

## Coercion

<div class='hide' data-tag='Coercion'>
1. vector 內的每個元素，資料類型必須相同
1. 如果不同，R 會根據某些規則，自動幫你將某些資料類型轉換成另一種資料類型

```r
c(TRUE, FALSE, 3)      # logical & numeric
c(-1, "aa")            # numeric & character
c(FALSE, TRUE, "hi!")  # logical & character
c(TRUE, 0, "hi!")      # logical & numeric & character
```

1. **slide**: Rules of Coercion
    - 能階圖：不同資料類型碰在一起，比較上面的那個就會變成比較下面的那個資料類型
    - 其實這個 Rules of coercion 還蠻有邏輯的，因為位在越下方的資料類型，它能夠儲存的東西其實越多元 (換句話說，能表徵越複雜的東西)
    - logical --> numeric: 方便的 Coercion Rule


1. **Back to RStudio**：`sum()`
    1. 除了遇到不同資料類型時，R 會自動進行這種 coercion 外，你在執行某些函數的時候，這種 coercion 也可能會發生
    1. 例如，`sum()` 做的事是將你傳入的 numeric vector 的所有元素加起來，
        - numeric --> logical

```r
sum(1:10)
sum(c(TRUE, TRUE, FALSE))

gender <- c("male", "female", "male", "female")
gender == "male"
sum(gender == "male")  # num of male
mean(gender == "male")  # proportion of male
```
</div>


## Subsetting

<div class='hide' data-tag='Subsetting a vector'>
**slide**: 3 種篩選的方式

1. index
1. 等長的 logical vector
1. (特殊情況) 名字

**Demo**

1. Index Subsetting

    ```r
    letters
    letters[1]  # 第一個
    letters[length(letters)]  # 最後一個
    
    # 若要篩選出 1 個以上...
    letters[c(1, 3, 5)] 
    letters[1:5]
    letters[-(1:5)]  # 除了 1:5
    ```

2. Logical Subsetting

    ```r
    vec <- 1:4
    
    vec[c(T, T, F, F)]
    vec[c(T, T, T, F)]

    # Explain: 前面講過 logical test 可以用來產生 logical vector...
    vec[vec > 1]
    ```

3. Subsetting with names

    ```r
    # Explain: add names to vector
    age <- c('kai' = 40, 'jessy' = 20, 'joy' = 18, 'yola' = 19)
    age

    age['kai']
    age[c('kai', 'joy')]
    ```
</div>

## Modifying values

<div class='hide' data-tag='Modifying values in vector'>
1. 改一個 --> 改多個 --> Recycling 

    ```r
    a2z <- letters
    a2z

    # 改一個
    a2z[1] <- "A"
    a2z

    # 改多個
    a2z[c(3, 5)] <- c("C", "E")
    a2z

    # Recycling
    a2z[c(3, 5)] <- "hello"
    a2z
    ```

2. 使用 logical test 篩選出要更改的元素，再修改

    ```r
    gender <- c('m', 'f', 'm', 'f')
    gender[gender == 'm']

    # 改名字 1
    gender[gender == 'm'] <- 'male'
    gender

    # 改名字 2
    gender[gender == 'f'] <- 'female'
    gender
    ```
</div>

## if else

<div class='hide' data-tag='Openning'>
到目前為止，我們都是以**序列式**的方式去執行 R 的指令。  
換言之，如果你將到目前學到的所有 R 指令打在一份 RScript 裡面，  
你只能「由上到下」地，一行一行的去執行這些指令。

但是有時候，我們在執行 R 時，不希望去執行「每一行」的程式碼。  
我們可能會希望**依據情況的不同，能夠去執行「特定」的程式碼**。  
這時候，我們就會用到所謂的**條件式**，也就是 if-else。
</div>


<div class='hide' data-tag='if-else'>
1. 
    ```r
    x <- 1  # need to change to neg
    if (x > 0) {
        print('x is positive')
    }
    ```

1. 
    ```r
    x <- -1  
    if (x > 0) {
        print('x is positive')
    } else {
        print('x is not positive')
    }
    ```

1. 
    ```r
    x <- 0  # changed to zero
    if (x > 0) {
        print('x is positive')
    } else if (x == 0) {
        print('x is zero')
    } else {
        print('x is negative')
    }
    ```

1.  `x <- 1` 皆符合 `x > 0` 與 `x >= 0`

    ```r
    # 跳出條件式
    x <- 1  # changed to one
    if (x > 0) {
        print('x is positive')
    } else if (x >= 0) {
        print('x is greater than zero')  # message changed!
    } else {
        print('x is negative')
    }
    ```

</div>