---
title: "Data Visualization with ggplot2 (W7)"
date: '2019-10-24'
output:
    html_document:
        number_sections: no
        theme: united
        highlight: tango
        toc: yes
        toc_float:
            collapsed: no
        css: style.css
        md_extensions: +implicit_figures
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T,
                      results = 'hide',
                      comment = '#>',
                      message = F,
                      out.width = '80%',
                      fig.align = 'center')
library(ggplot2)
```

```{js echo=FALSE}
window.onload = () => {
        document.querySelectorAll('.hide').forEach(ele => {
            ele.className = 'note';
        })
}
```

## data: `diamonds`

`diamonds.R`

<div class="hide" data-tag="slide, demo">
**slide**

1. 介紹 `ggplot2` 內建資料 `diamonds`
    - row: 一個鑽石
    - col: 鑽石的屬性

2. 因為 diamonds 很大，電腦速度不夠，所以抽取 1500 筆資料

**demo**

1. 匯入資料：`diamonds.R`
</div>



## Template 1, 圖層

<div class="hide" data-tag="slide, demo">

**slide**

1. All plots are based on this template
    - 填入 slots 就好

2. 繪製散布圖

3. What are the layers doing?  
    
    1. `ggplot()`: 初始化、global-local (`data = diam` 可被後面的函數「看到」)
    2. `geom_point()`: 疊上新圖層、專責繪製散布圖

**demo**

1. 初始化：只有底圖

    ```r
    ggplot()
    # ggplot(data = diam)
    ```
2. 疊上新圖層，繪製散布圖

    ```r
    ggplot(data = diam) +
      geom_point(mapping = aes(x = carat, y = price))
    ```

3. Multiple layers

    ```r
    ggplot(data = diam) +
      geom_point(mapping = aes(x = carat, y = price)) +
      geom_smooth(mapping = aes(x = carat, y = price))
    
    # Switch layers  
    ggplot(data = diam) +
      geom_smooth(mapping = aes(x = carat, y = price)) +
      geom_point(mapping = aes(x = carat, y = price))
    ```

4. global & local

    ```r
    ggplot(data = diam, mapping = aes(x = carat, y = price)) +
      geom_smooth() +
      geom_point()
      
    ```

5. 忽略變項名稱 (第一個 argument)

    ```r
    ggplot(diam) +
      geom_smooth(aes(x = carat, y = price)) +
      geom_point(aes(x = carat, y = price))
    ```
</div>

**3 min**


## Mappings

<div class="hide" data-tag="slide">
**slide**

1. Mappings: 抽象資料對應到「實際可見」的視覺屬性  
2. **不同 geom function 有不同的 Mapping**
    - e.g. 長條圖 (和散布圖長得不一樣 --> Mapping 不同)
    - ggplot 難在領域知識：  
    要知道如何繪製統計圖前，必須具備基礎統計知識
    繪製地圖 --> 經緯座標、地圖投影 知識
3. **Your Turn**
</div>

**3 min**

<div class="hide" data-tag="demo, slide">
**demo**: `color = clarity` (類別) vs. `color = carat` (連續)

1. 
    ```r
    ggplot(diam) + 
      geom_point(aes(x = carat, y = price, color = clarity))
    
    ggplot(diam) + 
      geom_point(aes(x = carat, y = price, color = carat))
    ```

**slide**: pop quiz

- 改變 (全部的) 點的顏色**並非 mapping**
</div>


## Bar Chart, stat transform

<div class="hide" data-tag="slide, demo">

**demo**

1. geom_bar structure

    ```r
    ggplot(diam) +
      geom_bar(aes(x = cut))
    ```

2. Summarised data 

    ```r
    summarised <- diam %>%
      group_by(cut) %>%
      summarise(count = n())
    
    # "identity": 忽略 statistical transformation, 
    # 直接將變項對應至 x, y 軸
    ggplot(summarised) +
      geom_bar(aes(x = cut, y = count), stat = "identity")
    ```

3. Indentity

    ```r
    ggplot(diam) +
      geom_point(aes(carat, price), stat = "identity")
      
    ggplot(diam) +
      geom_point(aes(carat, price))
    ```
</div>
  
## Position Adjustments

<div class="hide" data-tag="slide">
1. `geom_bar` 可提供第二個 mapping: `fill`
1. 缺點：不易閱讀 (上下緣對應至 y 軸) --> 可修改 `position`
1. 預設：`position = "stack"` --> 看到各種 `cut` 之下，`clarity` 各類別的**絕對次數**
1. `"dodge"`
1. `"fill"`
</div>

**3 min**

## Facet

<div class="hide" data-tag="slide, demo">
**slide**

1. 連結：一開始的散布圖
    - 使用**所有**的**觀察值**繪製散布圖
1. 看 **Local** 的情況：  
某個類別變項下的某個種類的散布情況

**demo**

1. **一個**變項

    ```r
    # 先畫出原本的散布圖
    ggplot(diam) +
      geom_point(aes(carat, price))
    
    ggplot(diam) +
      geom_point(aes(carat, price)) +
      facet_wrap(vars(cut))
    ```

2. **兩個**變項：兩類別變項下，**各種情況的組合**

    ```r
    ggplot(diam) +
      geom_point(aes(carat, price)) +
      facet_grid(vars(cut), vars(clarity))
    ```
</div>

