---
title: "中文文本資料處理 (W10)"
date: '2019-11-14'
output:
  html_document:
    number_sections: no
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: false
    css: style.css
    md_extensions: +implicit_figures
    includes:
      in_header: "../GA.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment = '#>',message = F, out.width = '70%', fig.align='center')
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'),color = 'darkred', lang=c('r', 'txt'))
```


```{r}
library(jiebaR)
library(stringr)

fps <- list.files("dcard", full.names = T)

titles <- vector("character", length(fps))
topics <- vector("character", length(fps))
contents <- vector("character", length(fps))
for (i in seq_along(fps)) {
  # Get topic from file name
  topics[i] <- str_split(basename(fps[i]), "_")[[1]][1]
  
  # Read post from file
  post <- readLines(fps[i])
  
  # Get post title (First line of file)
  titles[i] <- post[1] %>% stringr::str_match("【(\\S+)】") %>% .[1, 2]
    
  # Segment post
  seg <- worker(bylines = F, symbol = T)
  segged <- segment(post, seg)
  contents[i] <- segged %>% trimws() %>% paste(collapse = " ")
}


# Combine results in a df
df <- tibble::tibble(title = titles, topics = topic, content = content)
df
```



